### ISSUE TITLE
Continue refining scenarios

### ISSUE THREAD

**Issue by mchaf0126** [mchaf0126/pod_lca_data_analysis#7]
- [x] mchaf0126/pod_lca_data_analysis#8 
- [x] mchaf0126/pod_lca_data_analysis#9 
- [x] mchaf0126/pod_lca_data_analysis#10 
- [x] mchaf0126/pod_lca_data_analysis#11
